<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="SetSymbols\*.svg" />
    <EmbeddedResource Include="ManaSymbols\*.svg" />
    <EmbeddedResource Include="Frames\Token\*.png" />
    <EmbeddedResource Include="Frames\Storybook\*.png" />
    <EmbeddedResource Include="Frames\Modal\*.png" />
    <EmbeddedResource Include="Frames\ShortModal\*.png" />
    <EmbeddedResource Include="Frames\Unstable\*.png" />
    <EmbeddedResource Include="Frames\Planeswalker\*.png" />
    <EmbeddedResource Include="Frames\PlaneswalkerNickname\*.png" />
    <EmbeddedResource Include="Frames\Expedition\*.png" />
    <EmbeddedResource Include="Frames\ExpeditionNew\*.png" />
    <EmbeddedResource Include="Frames\Future\*.png" />
    <EmbeddedResource Include="Frames\Ixalan\*.png" />
    <EmbeddedResource Include="Frames\Modern\*.png" />
    <EmbeddedResource Include="Frames\ModernBoxTopper\*.png" />
    <EmbeddedResource Include="Frames\ModernCommanderLegends\*.png" />
    <EmbeddedResource Include="Frames\ModernCustom\*.png" />
    <EmbeddedResource Include="Frames\ModernDevoid\*.png" />
    <EmbeddedResource Include="Frames\ModernGenericShowcase\*.png" />
    <EmbeddedResource Include="Frames\ModernHoloStamps\*.png" />
    <EmbeddedResource Include="Frames\ModernInvention\*.png" />
    <EmbeddedResource Include="Frames\ModernInventionClassic\*.png" />
    <EmbeddedResource Include="Frames\ModernM21\*.png" />
    <EmbeddedResource Include="Frames\ModernNickname\*.png" />
    <EmbeddedResource Include="Frames\ModernNyx\*.png" />
    <EmbeddedResource Include="Frames\ModernZendikarRising\*.png" />
    <EmbeddedResource Include="Frames\ModernPromo\*.png" />
  </ItemGroup>

</Project>
